ISIviewer: Pyramid Class Reference
Pyramid Class Reference
#include <pyramid.h>
Public Member Functions
Pyramid ()
virtual ~Pyramid ()
Public Member Functions inherited from TriMesh
TriMesh ()
virtual ~TriMesh ()
virtual void draw (bool flipnormals=false)
virtual void drawNormals (bool flipnormals=false)
virtual void drawVertices ()
void addVertex (Vertex v)
void addVertex (double x, double y, double z)
void addTriangle (Triangle t)
void addTriangle (int v1, int v2, int v3)
void addNormalT (Normal n)
void addNormalV (Normal n)
Vertex getVertex (int index)
virtual std::string toString ()
virtual void toOStream (std::ostream &out=std::cout) const
void computeBoundingBox ()
void computeNormalsT ()
void computeNormalsV (float threshold=70.)
double normalize ()
Public Member Functions inherited from Object3D
Object3D ()
virtual ~Object3D ()
std::string getName ()
void setName (std::string name)
glm::vec3 getBoundingBoxCenter ()
Additional Inherited Members
Protected Member Functions inherited from Object3D
void extendBoundingBox (glm::vec3 newVertex)
Protected Attributes inherited from TriMesh
std::vector< Vertex > _vertices
std::vector< Triangle > _triangles
std::vector< Normal > _normalsT
std::vector< Normal > _normalsV
Protected Attributes inherited from Object3D
std::string _name
glm::vec3 _bBoxMin
glm::vec3 _bBoxMax
bool _bBempty
Detailed Description
Author
Bruno Jobard
Date
Oct 2012
Defines a 3D pyramid Pyramid object
Definition at line 17 of file pyramid.h.
Constructor & Destructor Documentation
Pyramid::Pyramid ()
Definition at line 5 of file pyramid.cpp.
References Object3D::_name, TriMesh::addTriangle(), TriMesh::addVertex(), TriMesh::computeNormalsT(), and TriMesh::computeNormalsV().
virtual Pyramid::~Pyramid () inline virtual
Definition at line 21 of file pyramid.h.
The documentation for this class was generated from the following files:
objects/pyramid.h
objects/pyramid.cpp