ISIviewer: MyScene Class Reference
MyScene Class Reference
#include <my_scene.h>
Public Slots
void slotSetCurrentObject (int co)
void slotSetDisplayMode (int dm)
void slotSetRadius (double radius)
void slotSetWireframe (bool on)
void slotSetSmooth (bool on)
void slotSetDisplayNormals (bool on)
void slotSetFlipNormals (bool on)
Signals
void sigCurrentObjectChanged (int co)
void sigDisplayModeChanged (int dm)
void sigRadiusChanged (double radius)
void sigWireframeChanged (bool on)
void sigSmoothChanged (bool on)
void sigDisplayNormalsChanged (bool on)
void sigFlipNormalsChanged (bool on)
Public Member Functions
MyScene (float radius=1.)
virtual ~MyScene ()
void setCurrentObject (int co)
int currentObject ()
void setDisplayMode (int dm)
int displayMode ()
void setRadius (float radius)
float radius ()
double radiusMin ()
double radiusMax ()
double radiusIncr ()
void init ()
void draw ()
void addObject (Object3D *)
bool keyPressEvent (QKeyEvent *e)
Protected Attributes
std::vector< Object3D * > _objects
int _currentObject
float _radius
int _displayMode
bool _normalsFlipped
bool _displayWireframe
double _radiusMin
double _radiusMax
double _radiusIncr
Private Types
enum displayModeType { WIREFRAME =1, SMOOTH =2, NORMALS =4 }
Detailed Description
Definition at line 20 of file my_scene.h.
Member Enumeration Documentation
enum MyScene::displayModeType private
Enumerator
WIREFRAME
SMOOTH
NORMALS
Definition at line 24 of file my_scene.h.
Constructor & Destructor Documentation
MyScene::MyScene (float radius = 1.)
Constructor
Parameters
radius
Definition at line 15 of file my_scene.cpp.
MyScene::~MyScene () virtual
Destructor
Definition at line 36 of file my_scene.cpp.
Member Function Documentation
void MyScene::addObject (Object3D * o)
Definition at line 232 of file my_scene.cpp.
Referenced by radiusIncr().
int MyScene::currentObject () inline
Definition at line 46 of file my_scene.h.
References _currentObject.
int MyScene::displayMode () inline
Definition at line 48 of file my_scene.h.
References _displayMode.
void MyScene::draw ()
Draw the scene
Definition at line 59 of file my_scene.cpp.
References NORMALS, SMOOTH, and WIREFRAME.
Referenced by radiusIncr().
void MyScene::init ()
Init the scene and OpenGL state
Definition at line 44 of file my_scene.cpp.
Referenced by radiusIncr().
bool MyScene::keyPressEvent (QKeyEvent * e)
Process keyboard events for QGLViewer widget
Parameters
e a keyboard event from QGLViewer
Returns
true if the event has been handled
Definition at line 174 of file my_scene.cpp.
References NORMALS, SMOOTH, and WIREFRAME.
Referenced by radiusIncr().
float MyScene::radius () inline
Definition at line 51 of file my_scene.h.
References _radius.
Referenced by radiusIncr(), and setRadius().
double MyScene::radiusIncr () inline
Definition at line 54 of file my_scene.h.
References _radiusIncr, addObject(), draw(), init(), keyPressEvent(), radius(), sigCurrentObjectChanged(), sigDisplayModeChanged(), sigDisplayNormalsChanged(), sigFlipNormalsChanged(), sigRadiusChanged(), sigSmoothChanged(), sigWireframeChanged(), slotSetCurrentObject(), slotSetDisplayMode(), slotSetDisplayNormals(), slotSetFlipNormals(), slotSetRadius(), slotSetSmooth(), and slotSetWireframe().
double MyScene::radiusMax () inline
Definition at line 53 of file my_scene.h.
References _radiusMax.
double MyScene::radiusMin () inline
Definition at line 52 of file my_scene.h.
References _radiusMin.
void MyScene::setCurrentObject (int co) inline
Definition at line 45 of file my_scene.h.
void MyScene::setDisplayMode (int dm) inline
Definition at line 47 of file my_scene.h.
void MyScene::setRadius (float radius) inline
Definition at line 50 of file my_scene.h.
References radius().
void MyScene::sigCurrentObjectChanged (int co) signal
Referenced by radiusIncr().
void MyScene::sigDisplayModeChanged (int dm) signal
Referenced by radiusIncr().
void MyScene::sigDisplayNormalsChanged (bool on) signal
Referenced by radiusIncr().
void MyScene::sigFlipNormalsChanged (bool on) signal
Referenced by radiusIncr().
void MyScene::sigRadiusChanged (double radius) signal
Referenced by radiusIncr().
void MyScene::sigSmoothChanged (bool on) signal
Referenced by radiusIncr().
void MyScene::sigWireframeChanged (bool on) signal
Referenced by radiusIncr().
void MyScene::slotSetCurrentObject (int currentObject) slot
Slot set current object
Parameters
currentObject
Definition at line 124 of file my_scene.cpp.
Referenced by radiusIncr().
void MyScene::slotSetDisplayMode (int displayMode) slot
Slot set display mode
Parameters
displayMode
Definition at line 141 of file my_scene.cpp.
References NORMALS, SMOOTH, and WIREFRAME.
Referenced by radiusIncr().
void MyScene::slotSetDisplayNormals (bool on) slot
Definition at line 108 of file my_scene.cpp.
References NORMALS.
Referenced by radiusIncr().
void MyScene::slotSetFlipNormals (bool on) slot
Definition at line 114 of file my_scene.cpp.
Referenced by radiusIncr().
void MyScene::slotSetRadius (double radius) slot
Slot set radius
Parameters
radius
Definition at line 158 of file my_scene.cpp.
Referenced by radiusIncr().
void MyScene::slotSetSmooth (bool on) slot
Definition at line 102 of file my_scene.cpp.
References SMOOTH.
Referenced by radiusIncr().
void MyScene::slotSetWireframe (bool on) slot
Definition at line 96 of file my_scene.cpp.
References WIREFRAME.
Referenced by radiusIncr().
Member Data Documentation
int MyScene::_currentObject protected
id of the current displayed 3D object
Definition at line 30 of file my_scene.h.
Referenced by currentObject().
int MyScene::_displayMode protected
current display mode
Definition at line 32 of file my_scene.h.
Referenced by displayMode().
bool MyScene::_displayWireframe protected
display the triangle mesh in wireframe?
Definition at line 34 of file my_scene.h.
bool MyScene::_normalsFlipped protected
flip triangle normals?
Definition at line 33 of file my_scene.h.
std::vector<Object3D*> MyScene::_objects protected
all 3D objects
Definition at line 27 of file my_scene.h.
float MyScene::_radius protected
radius of the object in the rendering window
Definition at line 31 of file my_scene.h.
Referenced by radius().
double MyScene::_radiusIncr protected
Definition at line 39 of file my_scene.h.
Referenced by radiusIncr().
double MyScene::_radiusMax protected
Definition at line 38 of file my_scene.h.
Referenced by radiusMax().
double MyScene::_radiusMin protected
Definition at line 37 of file my_scene.h.
Referenced by radiusMin().
The documentation for this class was generated from the following files:
my_scene.h
my_scene.cpp