ISIviewer: Sphere Class Reference
Sphere Class Reference
#include <sphere.h>
Public Member Functions
void traceVertex ()
void traceTrianglesHaut ()
void traceTrianglesCentre ()
void traceTrianglesBas ()
Sphere ()
Sphere (int inc)
virtual ~Sphere ()
Public Member Functions inherited from TriMesh
TriMesh ()
virtual ~TriMesh ()
virtual void draw (bool flipnormals=false)
virtual void drawNormals (bool flipnormals=false)
virtual void drawVertices ()
void addVertex (Vertex v)
void addVertex (double x, double y, double z)
void addTriangle (Triangle t)
void addTriangle (int v1, int v2, int v3)
void addNormalT (Normal n)
void addNormalV (Normal n)
Vertex getVertex (int index)
virtual std::string toString ()
virtual void toOStream (std::ostream &out=std::cout) const
void computeBoundingBox ()
void computeNormalsT ()
void computeNormalsV (float threshold=70.)
double normalize ()
Public Member Functions inherited from Object3D
Object3D ()
virtual ~Object3D ()
std::string getName ()
void setName (std::string name)
glm::vec3 getBoundingBoxCenter ()
Protected Attributes
float m_x
float m_y
float m_z
float m_rayon
int m_inc
float m_angle_theta
float m_angle_phi
float m_niveau
Protected Attributes inherited from TriMesh
std::vector< Vertex > _vertices
std::vector< Triangle > _triangles
std::vector< Normal > _normalsT
std::vector< Normal > _normalsV
Protected Attributes inherited from Object3D
std::string _name
glm::vec3 _bBoxMin
glm::vec3 _bBoxMax
bool _bBempty
Additional Inherited Members
Protected Member Functions inherited from Object3D
void extendBoundingBox (glm::vec3 newVertex)
Detailed Description
Definition at line 8 of file sphere.h.
Constructor & Destructor Documentation
Sphere::Sphere ()
Sphere::Sphere (int inc)
Definition at line 78 of file sphere.cpp.
References Object3D::_name, TriMesh::addVertex(), TriMesh::computeNormalsT(), TriMesh::computeNormalsV(), m_angle_phi, m_angle_theta, m_inc, m_rayon, m_x, m_y, m_z, traceTrianglesBas(), traceTrianglesCentre(), traceTrianglesHaut(), and traceVertex().
virtual Sphere::~Sphere () inline virtual
Definition at line 19 of file sphere.h.
References m_x.
Member Function Documentation
void Sphere::traceTrianglesBas ()
Definition at line 65 of file sphere.cpp.
References TriMesh::addTriangle(), and m_inc.
Referenced by Sphere().
void Sphere::traceTrianglesCentre ()
Definition at line 44 of file sphere.cpp.
References TriMesh::addTriangle(), and m_inc.
Referenced by Sphere().
void Sphere::traceTrianglesHaut ()
Definition at line 34 of file sphere.cpp.
References TriMesh::addTriangle(), and m_inc.
Referenced by Sphere().
void Sphere::traceVertex ()
Definition at line 9 of file sphere.cpp.
References TriMesh::addVertex(), m_angle_phi, m_angle_theta, m_inc, m_rayon, and PI.
Referenced by Sphere().
Member Data Documentation
float Sphere::m_angle_phi protected
Definition at line 29 of file sphere.h.
Referenced by Sphere(), and traceVertex().
float Sphere::m_angle_theta protected
Definition at line 28 of file sphere.h.
Referenced by Sphere(), and traceVertex().
int Sphere::m_inc protected
Definition at line 27 of file sphere.h.
Referenced by Sphere(), traceTrianglesBas(), traceTrianglesCentre(), traceTrianglesHaut(), and traceVertex().
float Sphere::m_niveau protected
Definition at line 30 of file sphere.h.
float Sphere::m_rayon protected
Definition at line 26 of file sphere.h.
Referenced by Sphere(), and traceVertex().
float Sphere::m_x protected
Definition at line 19 of file sphere.h.
Referenced by Sphere(), and ~Sphere().
float Sphere::m_y protected
Definition at line 24 of file sphere.h.
Referenced by Sphere().
float Sphere::m_z protected
Definition at line 25 of file sphere.h.
Referenced by Sphere().
The documentation for this class was generated from the following files:
objects/sphere.h
objects/sphere.cpp