ISIviewer: DiskHole Class Reference
DiskHole Class Reference
#include <diskhole.h>
Public Member Functions
void traceVertex ()
void traceTriangles ()
DiskHole ()
DiskHole (float rayon, int inc)
virtual ~DiskHole ()
Public Member Functions inherited from TriMesh
TriMesh ()
virtual ~TriMesh ()
virtual void draw (bool flipnormals=false)
virtual void drawNormals (bool flipnormals=false)
virtual void drawVertices ()
void addVertex (Vertex v)
void addVertex (double x, double y, double z)
void addTriangle (Triangle t)
void addTriangle (int v1, int v2, int v3)
void addNormalT (Normal n)
void addNormalV (Normal n)
Vertex getVertex (int index)
virtual std::string toString ()
virtual void toOStream (std::ostream &out=std::cout) const
void computeBoundingBox ()
void computeNormalsT ()
void computeNormalsV (float threshold=70.)
double normalize ()
Public Member Functions inherited from Object3D
Object3D ()
virtual ~Object3D ()
std::string getName ()
void setName (std::string name)
glm::vec3 getBoundingBoxCenter ()
Protected Attributes
float m_x
float m_y
float m_z
float m_rayon
int m_inc
float m_angle
Protected Attributes inherited from TriMesh
std::vector< Vertex > _vertices
std::vector< Triangle > _triangles
std::vector< Normal > _normalsT
std::vector< Normal > _normalsV
Protected Attributes inherited from Object3D
std::string _name
glm::vec3 _bBoxMin
glm::vec3 _bBoxMax
bool _bBempty
Additional Inherited Members
Protected Member Functions inherited from Object3D
void extendBoundingBox (glm::vec3 newVertex)
Detailed Description
Definition at line 8 of file diskhole.h.
Constructor & Destructor Documentation
DiskHole::DiskHole ()
DiskHole::DiskHole (float rayon, int inc)
Definition at line 37 of file diskhole.cpp.
References Object3D::_name, TriMesh::addVertex(), TriMesh::computeNormalsT(), TriMesh::computeNormalsV(), m_angle, m_inc, m_rayon, m_x, m_y, m_z, traceTriangles(), and traceVertex().
virtual DiskHole::~DiskHole () inline virtual
Definition at line 17 of file diskhole.h.
References m_x.
Member Function Documentation
void DiskHole::traceTriangles ()
Definition at line 15 of file diskhole.cpp.
References TriMesh::addTriangle(), and m_inc.
Referenced by DiskHole().
void DiskHole::traceVertex ()
Definition at line 3 of file diskhole.cpp.
References TriMesh::addVertex(), m_angle, m_inc, m_rayon, and m_z.
Referenced by DiskHole().
Member Data Documentation
float DiskHole::m_angle protected
Definition at line 25 of file diskhole.h.
Referenced by DiskHole(), and traceVertex().
int DiskHole::m_inc protected
Definition at line 24 of file diskhole.h.
Referenced by DiskHole(), traceTriangles(), and traceVertex().
float DiskHole::m_rayon protected
Definition at line 23 of file diskhole.h.
Referenced by DiskHole(), and traceVertex().
float DiskHole::m_x protected
Definition at line 17 of file diskhole.h.
Referenced by DiskHole(), and ~DiskHole().
float DiskHole::m_y protected
Definition at line 21 of file diskhole.h.
Referenced by DiskHole().
float DiskHole::m_z protected
Definition at line 22 of file diskhole.h.
Referenced by DiskHole(), and traceVertex().
The documentation for this class was generated from the following files:
objects/diskhole.h
objects/diskhole.cpp