ISIviewer: Disk Class Reference
Disk Class Reference
#include <disk.h>
Public Member Functions
void traceVertex ()
void traceTriangles ()
Disk ()
Disk (int inc)
virtual ~Disk ()
Public Member Functions inherited from TriMesh
TriMesh ()
virtual ~TriMesh ()
virtual void draw (bool flipnormals=false)
virtual void drawNormals (bool flipnormals=false)
virtual void drawVertices ()
void addVertex (Vertex v)
void addVertex (double x, double y, double z)
void addTriangle (Triangle t)
void addTriangle (int v1, int v2, int v3)
void addNormalT (Normal n)
void addNormalV (Normal n)
Vertex getVertex (int index)
virtual std::string toString ()
virtual void toOStream (std::ostream &out=std::cout) const
void computeBoundingBox ()
void computeNormalsT ()
void computeNormalsV (float threshold=70.)
double normalize ()
Public Member Functions inherited from Object3D
Object3D ()
virtual ~Object3D ()
std::string getName ()
void setName (std::string name)
glm::vec3 getBoundingBoxCenter ()
Protected Attributes
float m_x
float m_y
float m_z
float m_rayon
int m_inc
float m_angle
Protected Attributes inherited from TriMesh
std::vector< Vertex > _vertices
std::vector< Triangle > _triangles
std::vector< Normal > _normalsT
std::vector< Normal > _normalsV
Protected Attributes inherited from Object3D
std::string _name
glm::vec3 _bBoxMin
glm::vec3 _bBoxMax
bool _bBempty
Additional Inherited Members
Protected Member Functions inherited from Object3D
void extendBoundingBox (glm::vec3 newVertex)
Detailed Description
Definition at line 8 of file disk.h.
Constructor & Destructor Documentation
Disk::Disk ()
Disk::Disk (int inc)
Definition at line 29 of file disk.cpp.
References Object3D::_name, TriMesh::computeNormalsT(), TriMesh::computeNormalsV(), m_angle, m_inc, m_rayon, m_x, m_y, m_z, traceTriangles(), and traceVertex().
virtual Disk::~Disk () inline virtual
Definition at line 18 of file disk.h.
References m_x.
Member Function Documentation
void Disk::traceTriangles ()
Definition at line 19 of file disk.cpp.
References TriMesh::addTriangle(), and m_inc.
Referenced by Disk().
void Disk::traceVertex ()
Definition at line 4 of file disk.cpp.
References TriMesh::addVertex(), m_angle, m_inc, m_rayon, m_x, m_y, and m_z.
Referenced by Disk().
Member Data Documentation
float Disk::m_angle protected
Definition at line 26 of file disk.h.
Referenced by Disk(), and traceVertex().
int Disk::m_inc protected
Definition at line 25 of file disk.h.
Referenced by Disk(), traceTriangles(), and traceVertex().
float Disk::m_rayon protected
Definition at line 24 of file disk.h.
Referenced by Disk(), and traceVertex().
float Disk::m_x protected
Definition at line 18 of file disk.h.
Referenced by Disk(), traceVertex(), and ~Disk().
float Disk::m_y protected
Definition at line 22 of file disk.h.
Referenced by Disk(), and traceVertex().
float Disk::m_z protected
Definition at line 23 of file disk.h.
Referenced by Disk(), and traceVertex().
The documentation for this class was generated from the following files:
objects/disk.h
objects/disk.cpp