ISIviewer: TriMesh Class Reference
TriMesh Class Reference
#include <triMesh.h>
Public Member Functions
TriMesh ()
virtual ~TriMesh ()
virtual void draw (bool flipnormals=false)
virtual void drawNormals (bool flipnormals=false)
virtual void drawVertices ()
void addVertex (Vertex v)
void addVertex (double x, double y, double z)
void addTriangle (Triangle t)
void addTriangle (int v1, int v2, int v3)
void addNormalT (Normal n)
void addNormalV (Normal n)
Vertex getVertex (int index)
virtual std::string toString ()
virtual void toOStream (std::ostream &out=std::cout) const
void computeBoundingBox ()
void computeNormalsT ()
void computeNormalsV (float threshold=70.)
double normalize ()
Public Member Functions inherited from Object3D
Object3D ()
virtual ~Object3D ()
std::string getName ()
void setName (std::string name)
glm::vec3 getBoundingBoxCenter ()
Protected Attributes
std::vector< Vertex > _vertices
std::vector< Triangle > _triangles
std::vector< Normal > _normalsT
std::vector< Normal > _normalsV
Protected Attributes inherited from Object3D
std::string _name
glm::vec3 _bBoxMin
glm::vec3 _bBoxMax
bool _bBempty
Additional Inherited Members
Protected Member Functions inherited from Object3D
void extendBoundingBox (glm::vec3 newVertex)
Detailed Description
Simple Triangular Mesh Object
Definition at line 26 of file triMesh.h.
Constructor & Destructor Documentation
TriMesh::TriMesh ()
Definition at line 5 of file triMesh.cpp.
References Object3D::_name.
virtual TriMesh::~TriMesh () inline virtual
Definition at line 36 of file triMesh.h.
Member Function Documentation
void TriMesh::addNormalT (Normal n)
adds a triangle normal to the mesh
Parameters
n the normal to be added
Definition at line 28 of file triMesh.cpp.
References _normalsT.
Referenced by computeNormalsT(), and Cube::Cube().
void TriMesh::addNormalV (Normal n)
adds a vertex normal to the mesh
Parameters
n the normal to be added
Definition at line 31 of file triMesh.cpp.
References _normalsV.
Referenced by computeNormalsV(), and Cube::Cube().
void TriMesh::addTriangle (Triangle t)
adds a triangle to the mesh
Parameters
t the triangle to be added
Definition at line 18 of file triMesh.cpp.
References _triangles.
Referenced by addTriangle(), Cube::Cube(), CubeCorner::CubeCorner(), Func_surface::Func_surface(), Pyramid::Pyramid(), Torus::Torus(), DiskHole::traceTriangles(), Disk::traceTriangles(), Sphere::traceTrianglesBas(), Cylinder::traceTrianglesBase(), Cone::traceTrianglesBase(), Sphere::traceTrianglesCentre(), Cylinder::traceTrianglesCentre(), Sphere::traceTrianglesHaut(), Cone::traceTrianglesHaut(), Cylinder::traceTrianglesHaut(), and Cone::traceTrianglesMilieu().
void TriMesh::addTriangle (int v1, int v2, int v3)
adds a triangle to the mesh
Parameters
v1 first vertex of the triangle
v2 second vertex of the triangle
v3 third vertex of the triangle
Definition at line 21 of file triMesh.cpp.
References addTriangle().
void TriMesh::addVertex (Vertex v)
adds a vertex to the mesh
Parameters
v the vertex to be added
Definition at line 11 of file triMesh.cpp.
References _vertices, and Object3D::extendBoundingBox().
Referenced by addVertex(), Cone::Cone(), Cube::Cube(), CubeCorner::CubeCorner(), Cylinder::Cylinder(), DiskHole::DiskHole(), Func_surface::Func_surface(), Pyramid::Pyramid(), Sphere::Sphere(), Torus::Torus(), DiskHole::traceVertex(), Disk::traceVertex(), Sphere::traceVertex(), Cylinder::traceVertex(), and Cone::traceVertex().
void TriMesh::addVertex (double x, double y, double z)
adds a vertex to the mesh
Parameters
x the x coordinate of the vertex to be added
y the y coordinate of the vertex to be added
z the z coordinate of the vertex to be added
Definition at line 15 of file triMesh.cpp.
References addVertex().
void TriMesh::computeBoundingBox ()
updates the bouding box of the object
Definition at line 41 of file triMesh.cpp.
References Object3D::_bBoxMax, Object3D::_bBoxMin, _vertices, and Object3D::extendBoundingBox().
void TriMesh::computeNormalsT ()
computes the triangles normals of the 3D mesh
Definition at line 50 of file triMesh.cpp.
References _normalsT, _triangles, _vertices, and addNormalT().
Referenced by Cone::Cone(), Cube::Cube(), CubeCorner::CubeCorner(), Cylinder::Cylinder(), Disk::Disk(), DiskHole::DiskHole(), Func_surface::Func_surface(), Pyramid::Pyramid(), Sphere::Sphere(), and Torus::Torus().
void TriMesh::computeNormalsV (float threshold = 70.)
computes the vertices normals of the 3D mesh.
it requires triangles normals to be computed first
See Also
computeNormalsT
Parameters
threshold the angles beyond which two faces are considered to have a sharp edge
Definition at line 83 of file triMesh.cpp.
References _normalsT, _normalsV, _triangles, and addNormalV().
Referenced by Cone::Cone(), Cube::Cube(), CubeCorner::CubeCorner(), Cylinder::Cylinder(), Disk::Disk(), DiskHole::DiskHole(), Func_surface::Func_surface(), Pyramid::Pyramid(), Sphere::Sphere(), and Torus::Torus().
void TriMesh::draw (bool flipnormals = false) virtual
draws the 3D object
Parameters
flipnormals specifies if normals are flipped (default is false, the triangles are counter clock-wise)
Reimplemented from Object3D.
Definition at line 156 of file triMesh.cpp.
References _normalsT, _normalsV, _triangles, and _vertices.
void TriMesh::drawNormals (bool flipnormals = false) virtual
draws the normals as line segments
Parameters
flipnormals specifies if normals are flipped (default is false, the triangles are counter clock-wise)
Reimplemented from Object3D.
Definition at line 191 of file triMesh.cpp.
References _normalsT, _normalsV, _triangles, and _vertices.
void TriMesh::drawVertices () virtual
draws the vertices as points
Definition at line 230 of file triMesh.cpp.
References _vertices.
Vertex TriMesh::getVertex (int index)
gets a vertex
Parameters
index the index of the vertex
Definition at line 36 of file triMesh.cpp.
References _vertices.
double TriMesh::normalize ()
scales and centers the objects so it fits in the [-1:1]^3
Returns
the scaling factor
Definition at line 123 of file triMesh.cpp.
References Object3D::_bBoxMax, Object3D::_bBoxMin, _vertices, and Object3D::getBoundingBoxCenter().
void TriMesh::toOStream (std::ostream & out = std::cout) const virtual
Send the state of the object to an output stream
Reimplemented from Object3D.
Definition at line 148 of file triMesh.cpp.
References _triangles, _vertices, and Object3D::toOStream().
std::string TriMesh::toString () virtual
Get the name of the object
Reimplemented from Object3D.
Definition at line 142 of file triMesh.cpp.
References Object3D::_name, _triangles, and _vertices.
Member Data Documentation
std::vector<Normal> TriMesh::_normalsT protected
Definition at line 31 of file triMesh.h.
Referenced by addNormalT(), computeNormalsT(), computeNormalsV(), draw(), and drawNormals().
std::vector<Normal> TriMesh::_normalsV protected
Definition at line 32 of file triMesh.h.
Referenced by addNormalV(), computeNormalsV(), draw(), and drawNormals().
std::vector<Triangle> TriMesh::_triangles protected
Definition at line 30 of file triMesh.h.
Referenced by addTriangle(), computeNormalsT(), computeNormalsV(), draw(), drawNormals(), toOStream(), and toString().
std::vector<Vertex> TriMesh::_vertices protected
Definition at line 29 of file triMesh.h.
Referenced by addVertex(), computeBoundingBox(), computeNormalsT(), draw(), drawNormals(), drawVertices(), getVertex(), normalize(), toOStream(), and toString().
The documentation for this class was generated from the following files:
objects/triMesh.h
objects/triMesh.cpp