ISIviewer: Func_surface Class Reference
Func_surface Class Reference
#include <func_surface.h>
Public Member Functions
Func_surface (int nbx, int nby, float minx, float maxx, float miny, float maxy, float(*pointeur)(float, float))
virtual ~Func_surface ()
float func_rand (float min, float max)
Public Member Functions inherited from TriMesh
TriMesh ()
virtual ~TriMesh ()
virtual void draw (bool flipnormals=false)
virtual void drawNormals (bool flipnormals=false)
virtual void drawVertices ()
void addVertex (Vertex v)
void addVertex (double x, double y, double z)
void addTriangle (Triangle t)
void addTriangle (int v1, int v2, int v3)
void addNormalT (Normal n)
void addNormalV (Normal n)
Vertex getVertex (int index)
virtual std::string toString ()
virtual void toOStream (std::ostream &out=std::cout) const
void computeBoundingBox ()
void computeNormalsT ()
void computeNormalsV (float threshold=70.)
double normalize ()
Public Member Functions inherited from Object3D
Object3D ()
virtual ~Object3D ()
std::string getName ()
void setName (std::string name)
glm::vec3 getBoundingBoxCenter ()
Protected Attributes
int m_nbx
int m_nby
float m_minx
float m_maxx
float m_miny
float m_maxy
Protected Attributes inherited from TriMesh
std::vector< Vertex > _vertices
std::vector< Triangle > _triangles
std::vector< Normal > _normalsT
std::vector< Normal > _normalsV
Protected Attributes inherited from Object3D
std::string _name
glm::vec3 _bBoxMin
glm::vec3 _bBoxMax
bool _bBempty
Additional Inherited Members
Protected Member Functions inherited from Object3D
void extendBoundingBox (glm::vec3 newVertex)
Detailed Description
Definition at line 13 of file func_surface.h.
Constructor & Destructor Documentation
Func_surface::Func_surface (int nbx, int nby, float minx, float maxx, float miny, float maxy, float(*)(float, float) pointeur)
Definition at line 23 of file func_surface.cpp.
References Object3D::_name, TriMesh::addTriangle(), TriMesh::addVertex(), TriMesh::computeNormalsT(), TriMesh::computeNormalsV(), m_maxx, m_maxy, m_minx, m_miny, m_nbx, and m_nby.
virtual Func_surface::~Func_surface () inline virtual
Definition at line 18 of file func_surface.h.
Member Function Documentation
float Func_surface::func_rand (float min, float max)
Member Data Documentation
float Func_surface::m_maxx protected
Definition at line 26 of file func_surface.h.
Referenced by Func_surface().
float Func_surface::m_maxy protected
Definition at line 28 of file func_surface.h.
Referenced by Func_surface().
float Func_surface::m_minx protected
Definition at line 25 of file func_surface.h.
Referenced by Func_surface().
float Func_surface::m_miny protected
Definition at line 27 of file func_surface.h.
Referenced by Func_surface().
int Func_surface::m_nbx protected
Definition at line 23 of file func_surface.h.
Referenced by Func_surface().
int Func_surface::m_nby protected
Definition at line 24 of file func_surface.h.
Referenced by Func_surface().
The documentation for this class was generated from the following files:
objects/func_surface.h
objects/func_surface.cpp