ISIviewer: Object3D Class Reference
Object3D Class Reference
#include <my_object3d.h>
Public Member Functions
Object3D ()
virtual ~Object3D ()
std::string getName ()
void setName (std::string name)
virtual void draw (bool flipnormals=false)
virtual void drawNormals (bool flipnormals=false)
glm::vec3 getBoundingBoxCenter ()
virtual std::string toString ()
virtual void toOStream (std::ostream &out=std::cout) const
Protected Member Functions
void extendBoundingBox (glm::vec3 newVertex)
Protected Attributes
std::string _name
glm::vec3 _bBoxMin
glm::vec3 _bBoxMax
bool _bBempty
Friends
std::ostream & operator<< (std::ostream &out, const Object3D &obj3D)
Detailed Description
Base of a 3D object
Definition at line 36 of file my_object3d.h.
Constructor & Destructor Documentation
Object3D::Object3D ()
Object3D Constructor
Definition at line 12 of file my_object3d.cpp.
References _bBempty, _bBoxMax, _bBoxMin, and _name.
Object3D::~Object3D () virtual
Definition at line 21 of file my_object3d.cpp.
Member Function Documentation
void Object3D::draw (bool flipnormals = false) virtual
Draw the object
Draw an Object3D
Empty for this abstract Object3D
Reimplemented in TriMesh.
Definition at line 53 of file my_object3d.cpp.
Referenced by setName().
void Object3D::drawNormals (bool flipnormals = false) virtual
Draw the normals of the object
Reimplemented in TriMesh.
Definition at line 58 of file my_object3d.cpp.
Referenced by setName().
void Object3D::extendBoundingBox (glm::vec3 newVertex) protected
Extend the bounding box of an object with the new vertex
Parameters
newVertex extends the bounding box if it is outside the current bounding box
Definition at line 64 of file my_object3d.cpp.
References _bBempty, _bBoxMax, and _bBoxMin.
Referenced by TriMesh::addVertex(), TriMesh::computeBoundingBox(), and setName().
glm::vec3 Object3D::getBoundingBoxCenter ()
Get the center of the bounding box of the object
Definition at line 80 of file my_object3d.cpp.
References _bBoxMax, and _bBoxMin.
Referenced by TriMesh::normalize(), and setName().
std::string Object3D::getName () inline
Set and get the name of the object
Definition at line 51 of file my_object3d.h.
References _name.
void Object3D::setName (std::string name) inline
Definition at line 52 of file my_object3d.h.
References draw(), drawNormals(), extendBoundingBox(), getBoundingBoxCenter(), operator<<, toOStream(), and toString().
void Object3D::toOStream (std::ostream & out = std::cout) const virtual
Send the state of the object to an output stream
Reimplemented in TriMesh.
Definition at line 41 of file my_object3d.cpp.
References _name.
Referenced by operator<<(), setName(), and TriMesh::toOStream().
std::string Object3D::toString () virtual
Get the name of the object
Reimplemented in TriMesh.
Definition at line 38 of file my_object3d.cpp.
Referenced by setName().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Object3D & obj3D) friend
Print 3D object information in terminal
Parameters
out
obj3D
Returns
Definition at line 33 of file my_object3d.cpp.
Referenced by setName().
Member Data Documentation
bool Object3D::_bBempty protected
Is the Bounding box empty?
Definition at line 42 of file my_object3d.h.
Referenced by extendBoundingBox(), and Object3D().
glm::vec3 Object3D::_bBoxMax protected
Bounding box corners
Definition at line 41 of file my_object3d.h.
Referenced by TriMesh::computeBoundingBox(), extendBoundingBox(), getBoundingBoxCenter(), TriMesh::normalize(), and Object3D().
glm::vec3 Object3D::_bBoxMin protected
Definition at line 41 of file my_object3d.h.
Referenced by TriMesh::computeBoundingBox(), extendBoundingBox(), getBoundingBoxCenter(), TriMesh::normalize(), and Object3D().
std::string Object3D::_name protected
Object name
Definition at line 40 of file my_object3d.h.
Referenced by Cone::Cone(), Cube::Cube(), CubeCorner::CubeCorner(), Cylinder::Cylinder(), Disk::Disk(), DiskHole::DiskHole(), Func_surface::Func_surface(), getName(), Object3D(), Pyramid::Pyramid(), Sphere::Sphere(), toOStream(), Torus::Torus(), TriMesh::toString(), and TriMesh::TriMesh().
The documentation for this class was generated from the following files:
my_object3d.h
my_object3d.cpp